# Default configuration file for optimization with a hplane

# metadata
run_name: 'hplane'
fdm_bin: '/home/tunercar/flight-dynamics-model/bin/new_fdm'
fdm_wrapper_path: '/home/tunercar/fdm-wrapper'
propeller_path: '/home/tunercar/swri-uav-pipeline/uav-design-simulator/propeller'

# optim settings
# compute budget
budget: 9600
optim_method: 'CMA'
optim_params:
  popsize: 'default'
seed: 123

# path to design space file
acel_path: '/home/tunercar/swri-uav-pipeline/swri-uav-exploration/assets/uav_design_space.acel'

# path for saving the input output file
base_folder: '/home/tunercar/tunercar/es/evals'

# vehicle types:
# quadspider, quad, hcopter, hexring, hplane, hex
vehicle: 'hplane'

# design space
design_space:
  battery:
    # shape, num_selection
    [1, 27]
  esc:
    # shape, num_selection
    [5, 20]
  arm:
    # shape, num selection
    [12, 2]
  wing_support:
    # shape, num selection
    [2, 2]
  prop:
    # shape, num selection
    [5, 417]
  motor:
    # shape, num selection
    [5, 83]
  flange_support:
    # shape, num selection
    [4, 2]
  wing:
    # shape, num selection
    [2, 68]
  servo:
    # shape, num selection
    [2, 27]
  arm_length:
    # shape, min, max
    [12, 100.0, 1000.0]
  wing_support_length:
    # shape, min, max
    [2, 50.0, 300.0]
  flange_support_length:
    # shape, min, max
    [4, 50.0, 300.0]
  wing_offset:
    # shape, min, max
    [2, 100.0, 200.0]
  wing_span:
    # shape, min, max
    [2, 1000.0, 2000.0]
  wing_chord:
    # shape, min, max
    [2, 200.0, 400.0]
  LQR:
    # shape, min, max
    [20, 0.05, 3.0]
  lateral_velocity:
    # shape, min, max
    [4, 0.0, 20.0]
  vertical_velocity:
    # shape, min, max
    [4, -5.0, 5.0]