# Default configuration file for optimization with a quadrotor (4 propulsion blocks and 4 motors)

# metadata
run_name: 'default_quad'
fdm_bin: '/home/ray/flight-dynamics-model/bin/new_fdm'
fdm_wrapper_path: '/home/ray/fdm-wrapper'
propeller_path: '/home/ray/fdm-wrapper/propeller'

# optim settings
# compute budget
budget: 9600
optim_method: 'CMA'
optim_params:
  popsize: 'default'
seed: 12345

# operation range of parameters
# arm length of propulsion block
arm_length_min: 0.5
arm_length_max: 10.0

# battery parameters, all battery are the same if using multiple
# number of batteries
num_batteries:
  - 1 # all propulsion to 1
  - 2 # 1,2 to 1, 3,4 to 2
  - 3 # 1 to 1, 2 to 2, 3,4 to 3
  - 4 # each propulsion gets one

# Li-Po types (voltage)
battery_voltage:
  - 3.7
  - 7.4
  - 11.1

# battery capacity (mAh)
battery_capacity_min: 1000
battery_capacity_max: 5000
battery_mass_min: 0.10
battery_mass_max: 0.20