# Default configuration file for optimization with a quadrotor (4 propulsion blocks and 4 motors)

# metadata
run_name: 'default_quad'
fdm_bin: '/home/ray/flight-dynamics-model/bin/new_fdm'
fdm_wrapper_path: '/home/ray/fdm-wrapper'
propeller_path: '/home/ray/fdm-wrapper/propeller'

# optim settings
# compute budget
budget: 9600
optim_method: 'CMA'
optim_params:
  popsize: 'default'
seed: 12345

# vehicle types:
# quadspider, quad, hcopter, hexring, hplane, hex
vehicle: 'quad'

# operation range of parameters
# TODO
# new way of sampling parameters is through a selected vector
# e.g. for quad
# [batt,
#  esc1, esc2, esc3, esc4
#  arm1_tube, arm2_tube, arm3_tube, arm4_tube,
#  prop1, prop2, prop3, prop4,
#  motor1, motor2, motor3, motor4,
#  support1, support2, support3, support4,
#  arm1_length, arm2_length, arm3_length, arm4_length,
#  support1_length, support2_length, support3_length, support4_length,
#  Q_position,
#  Q_velocity,
#  Q_angular_velocity,
#  Q_angles,
#  control_R]

# arm length of propulsion block
arm_length_min: 0.5
arm_length_max: 10.0

# battery parameters, all battery are the same if using multiple
# number of batteries
num_batteries:
  - 1
  - 2
  - 3
  - 4

# Li-Po types (voltage)
battery_voltage:
  - 3.7
  - 7.4
  - 11.1

# battery capacity (mAh)
battery_capacity_min: 1000
battery_capacity_max: 5000
battery_mass_min: 0.10
battery_mass_max: 0.20